# Generated by Django 3.1.5 on 2021-01-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=30)),
                ('continent_code', models.CharField(max_length=2)),
                ('continent_name', models.CharField(max_length=20)),
                ('country_code', models.CharField(max_length=2)),
                ('country_name', models.CharField(max_length=60)),
                ('region_code', models.CharField(max_length=2)),
                ('region_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=15)),
                ('latitude', models.DecimalField(decimal_places=16, max_digits=22)),
                ('longitude', models.DecimalField(decimal_places=16, max_digits=22)),
            ],
        ),
    ]
